import type { Metadata } from 'next'

import '@/shared/styles/globals.css'

import type { ChildrenProps } from '@/types/children'

import { Toaster } from '@/shared/ui/sonner'

import { INTER, JETBRAINS_MONO, SPACE_GROTESK } from '@/fonts'
import { Providers } from '@/providers'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: ChildrenProps) {
	return (
		<html lang="en" suppressHydrationWarning={true}>
			<body className={`${JETBRAINS_MONO.variable} ${INTER.variable} ${SPACE_GROTESK.variable}`}>
				<Providers>{children}</Providers>
				<Toaster position="top-center" />
			</body>
		</html>
	)
}
